book_app/urls.py
from django.urls import path
from . import views


app_name = 'book'


urlpatterns = [
    path('', views.home, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('who-and-why/', views.who_why_view, name='who_why'),
    path('suggestion/', views.suggestion_view, name='suggestion'),
    path('add-book/', views.add_book, name='add_book'),
    path('<tag_slug>/', views.tag_details, name='tag_details'),
    path('book/<book_slug>/summary/', views.book_details, name='book_details'),
    path('book/<book_slug>/edit/', views.edit_book, name='edit_book'),
]

naveen_book_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ceo/', admin.site.urls),
    path('', include('book_app.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

book_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from tinymce import HTMLField

class TagModel(models.Model):
    tag_name = models.CharField(max_length=35)
    tag_slug = models.SlugField(unique=True, max_length=35)
    tag_added = models.DateTimeField(auto_now_add=True)
    tag_edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.tag_name

    class Meta:
        ordering = ['tag_name']
        verbose_name = 'Tags'
        verbose_name_plural = 'All Tags'


class BookModel(models.Model):
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    book_title = models.CharField(max_length=100)
    book_slug = models.SlugField(max_length=100, unique=True)
    book_author = models.CharField(max_length=120)
    author_quote = models.CharField(max_length=250, blank=True)
    author_description = models.TextField(blank=True)
    book_image_url = models.TextField()
    book_summary = HTMLField('book_summary')
    tag = models.ManyToManyField(TagModel, blank=True)
    book_publish_on = models.DateField(default=datetime.now)
    publish_status = models.BooleanField(default=True)
    book_added = models.DateTimeField(auto_now_add=True)
    book_edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.book_title

    class Meta:
        ordering = ['-book_added']


class SuggestionModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    book_name = models.CharField(max_length=100, blank=True)
    suggestion = models.TextField()
    suggestion_added = models.DateTimeField(auto_now_add=True)
    suggestion_edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name) + '-'  + str(self.email)

book_app/forms.py
from django import forms
from tinymce import TinyMCE
from .models import BookModel, SuggestionModel


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class SuggestionForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your Name*',
        'style': 'border-top: 0; border-right:0; border-left:0; color:#828282'
    }), label='', max_length=100)
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email*',
        'style': 'border-top: 0; border-right:0; border-left:0; color:#828282'
    }), label='')
    book_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Book Name',
        'style': 'border-top: 0; border-right:0; border-left:0; color:#828282'
    }), label='', max_length=100, required=False)
    suggestion = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 2,
        'class': 'form-control',
        'placeholder': 'Suggestion or Message*',
        'style': 'border-top: 0; border-right:0; border-left:0; color:#828282'
    }), label='', max_length=100)

    class Meta:
        model = SuggestionModel
        fields = ['name', 'email', 'book_name', 'suggestion']


class AddBookForm(forms.ModelForm):
    book_title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }), label='Book Title', max_length=100)
    book_author = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }), label='Book Author', max_length=120)
    book_image_url = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 3,
        'class': 'form-control',
    }), label='Book Image Url')
    book_summary = forms.CharField(widget=TinyMCEWidget(
            attrs={'class': 'form-control', 'required': False, 'rows': 10}
        ),label='Book Summary')
    book_publish_on = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'class': 'form-control w-50'
    })
    )
    publish_status = forms.BooleanField()

    class Meta:
        model = BookModel
        fields = ['book_title', 'book_author', 'book_image_url', 'book_summary', 'book_publish_on', 'tag', 'publish_status']


class EditBookForm(forms.ModelForm):
    book_title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }), label='Book Title', max_length=100)
    book_author = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }), label='Book Author', max_length=120)
    book_image_url = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 3,
        'class': 'form-control',
    }), label='Book Image Url')
    book_summary = forms.CharField(widget=TinyMCEWidget(attrs={
        'rows': 12,
    }), label='Book Summary')
    book_publish_on = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'class': 'form-control w-50'
    })
    )
    publish_status = forms.BooleanField()

    class Meta:
        model = BookModel
        fields = ['book_title', 'book_author', 'book_image_url', 'book_summary', 'book_publish_on', 'tag', 'publish_status']

book_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.messages import success
from django.utils.text import slugify
from django.contrib.auth import logout
from datetime import date
from .models import TagModel, BookModel
from .forms import AddBookForm, EditBookForm, SuggestionForm


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('book:home')
    else:
        return render(request, '404.html')


def home(request):
    all_tags = TagModel.objects.all()
    all_books = BookModel.objects.filter(book_publish_on__lte=date.today()).filter(publish_status=True)
    query = request.GET.get('q')
    if query:
        all_books = all_books.filter(book_title__icontains=query)
    return render(request, 'home.html', {'all_tags': all_tags, 'all_books': all_books, 'query': query})


def tag_details(request, tag_slug):
    tag = get_object_or_404(TagModel, tag_slug=tag_slug)
    tag_books = BookModel.objects.filter(tag=tag).filter(book_publish_on__lte=date.today()).filter(publish_status=True)
    return render(request, 'tag_details.html', {'tag': tag, 'tag_books': tag_books})


def book_details(request, book_slug):
    book = get_object_or_404(BookModel, book_slug=book_slug)
    return render(request, 'book_details.html', {'book': book})


def add_book(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            bookAdd = AddBookForm(request.POST or None)
            if bookAdd.is_valid():
                instance = bookAdd.save(commit=False)
                instance.book_slug = slugify(instance.book_title)
                instance.added_by = request.user
                instance.save()
                return redirect('book:home')
        else:
            bookAdd = AddBookForm()
        return render(request, 'add_book.html', {'bookAdd': bookAdd})
    else:
        return render(request, '404.html')


def edit_book(request, book_slug):
    if request.user.is_authenticated:
        book = get_object_or_404(BookModel, book_slug=book_slug)
        if request.method == 'POST':
            bookEdit = EditBookForm(request.POST, instance=book)
            if bookEdit.is_valid():
                bookEdit.save()
                return redirect('book:book_details', book.book_slug)
        else:
            bookEdit = EditBookForm(instance=book)
        return render(request, 'edit_book.html', {'bookEdit': bookEdit})
    else:
        return render(request, '404.html')  


def who_why_view(request):
    return render(request, 'who_why.html') 


def suggestion_view(request):
    if request.method == 'POST':
        s_form = SuggestionForm(request.POST or None)
        if s_form.is_valid:
            s_form.save()
            success(request, "Your suggestion has been submitted successfully.")
            return redirect("book:home")
    else:
        s_form = SuggestionForm()
    return render(request, 'suggestion_view.html', {'s_form': s_form})

book_app/templates/add_book.html
{% extends "base.html" %}

{% block title %}  Add book - Short Summary {% endblock title %}

{% block content %}

	
    {{ bookAdd.media }}
    <section  class='py-5  px-3'>
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 bg-white">
                <div class='px-5 pb-5 pt-4'>
                    <h2 class='text-center'>Add New Book</h2>
                    <form class="" method="post" action="{% url 'book:add_book' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ bookAdd.as_p }}
                        <button type='submit' class='btn btn-primary btn-block'>Add Summary</button>
                    </form>
                </div>
            </div>
        </div>
    </section>



{% endblock content %}

book_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock title %}</title>
    {% load static %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Basic|Gudea|Montserrat:500|Roboto&display=swap" rel="stylesheet">  
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
</head>
<body style="background-color:#F5F5F5">

    <nav class="navbar navbar-expand-lg pt-2 pt-md-1 pb-2 pb-md-3 " style="background-color: deepskyblue; color: white">
        <a class="navbar-brand text-white px-2 px-md-4" href="{% url 'book:home' %}">Short Summary</a>
        <button type="button" data-toggle="collapse" data-target="#navbarTarget" class="btn navbar-toggler border-0">
            <span><i class="fa fa-bars hamburger" aria-hidden="true"></i></span>
        </button>
        <div class="collapse navbar-collapse ml-lg-5" id="navbarTarget">
            <ul class="navbar-nav mr-auto ml-lg-1 ml-md-2">
                <li class="nav-item px-2 px-md-1 px-lg-2">
                    <a href="{% url 'book:home' %}" class="nav-link">Library</a>
                </li>
                <li class="nav-item px-2 px-md-1 px-lg-1">
                    <a href="{% url 'book:who_why' %}" class="nav-link">Who & Why ?</a>
                </li>
                <li class="nav-item px-2 px-md-1 px-lg-1">
                    <a href="{% url 'book:suggestion' %}" class="nav-link">Suggestions!</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item px-2 px-md-1 px-lg-1">
                        <a href="{% url 'book:logout' %}" class="nav-link text-danger">Logout</a>
                    </li>
                {% endif %}
            </ul>
            <form class="form-inline pr-2 pl-2 pl-md-2 mt-2 form-group" method="GET" action="{% url 'book:home' %}">
                <div class="input-group">
                    <input class="form-control rounded" placeholder="Book Title" type="search" name="q" value="{{ request.GET.q }}" aria-label="Search">
                    <button class="btn btn-dark mx-2" type="submit">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </div>
            </form>
        </div>
    </nav>


{% block content %}
{% endblock content %}


    


    <footer class="py-5 mt-5 px-3 px-md-5 text-white" style="background-color: deepskyblue">
        <div class="row px-0 px-md-3 py-3">
            <div class="col-lg-3 offset-lg-1 col-md-4 col-sm-6 pb-4">
                <h3 class="pb-2">Menu</h3>
                <a href="{% url 'book:home' %}" class="text-dark d-block py-2">Library
                </a>
                <a href="{% url 'book:suggestion' %}" class="text-dark d-block py-1">
                    Suggest a book
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 pb-4">
                <h3 class="pb-2">Reach Me</h3>
                <a href="https://www.instagram.com/magicalman78/" class="text-dark d-block py-2">
                     <i class="fa fa-instagram" aria-hidden="true"></i> Instagram
                </a>
                <a href="mailto:naveenchahar696@gmail.com" class="text-dark d-block py-2">
                     <i class="fa fa-envelope" aria-hidden="true"></i> Email
                </a>
                 <a href="https://www.facebook.com/magicalman78" class="text-dark d-block py-2">
                     <i class="fa fa-facebook" aria-hidden="true"></i> Facebook
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 pb-4">
                <h3 class="pb-2">Quote about reading</h3>
                <p class="text-dark py-2">“A reader lives a thousand lives before he dies. The man who never reads lives only one.” –George R R Martin</p>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

book_app/templates/book_details.html
{% extends 'base.html' %}

    {% block title %} {{ book.book_title }} - Short Summary {% endblock title %}

{% block content %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "book_details.css" %}">

    <section class="embed-responsive px-md-3 px-sm-4 px-3 py-5">
        <div class="row ">
            <div class="col-lg-8 offset-lg-2">
                <div class="py-3 py-md-3 px-3 px-md-5" style="background-color: white; border: lightgray solid 1px">
                    <h1 class="book-heading">{{ book.book_title }}</h1>
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-warning float-right" href="{% url 'book:edit_book' book.book_slug %}">Edit</a>
                    {% endif %}
                    <p class="text-muted font-italic">{{ book.book_author }}</p>

                    <div class="other-information" style="color: deepskyblue">
                        <span><i class="fa fa-calendar text-dark"></i>&nbsp;{{ book.book_publish_on | date }}</span> &nbsp;&nbsp;&nbsp;&nbsp;
                        <span><i class="fa fa-user text-dark"></i>&nbsp;{{ book.added_by.first_name }} {{ book.added_by.last_name }}</span>&nbsp;&nbsp;&nbsp;&nbsp;
                        <span><i class="fa fa-tags text-dark"></i>
                            {% for tags in book.tag.all %}
                                <a style="color: deepskyblue" href="{% url 'book:tag_details' tags.tag_slug %}">{{ tags }}, </a>
                            {% endfor %}
                        </span>&nbsp;&nbsp;
                    </div>

                    <p class="pt-4 book-summary">{{ book.book_summary | safe }}</p>

                </div>
            </div>
        </div>
    </section>

{% endblock content %}

book_app/templates/edit_book.html
{% extends "base.html" %}

{% block title %} Edit - Short Summary {% endblock title %}

{% block content %}
    {% load static %}

	
    {{ bookEdit.media }}
    <section class="py-5">
        <div class="container">
            <h2 class="pb-3">Edit Book Information</h2>
            <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ bookEdit.as_p }}
                <button type='submit' class='btn btn-primary'>Edit Summary</button>
            </form>
        </div>
    </section>


{% endblock content %}

book_app/templates/home.html
{% extends 'base.html' %}

{% block title %} Short Summary - Home {% endblock title %}


{% block content %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">

    {% if query %}
        <h3 class='text-muted px-3 text-center pt-4 pb-0'>Showing result for "{{ query }}" </h3>
    {% endif %}

    {% if all_tags %}

        <section class="embed-responsive py-5 px-md-5 px-sm-4 px-2 ">
            <div class="row px-3">
                <div class="col-12">
                    {% if messages %}
                        {% for message in messages %}
                           <div class="alert alert-success alert-dismissible">
                                {{ message }}
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="list-inline list-group-horizontal-sm p-0">
                        <p class="list-inline-item font-weight-normal lead bg-dark text-white pt-1 pb-2 px-3 my-1">Tags</p>
                        {% for tag in all_tags %}
                            <a href="{% url 'book:tag_details' tag.tag_slug %}" class="list-inline-item bg-light text-decoration-none my-1 p-2 border all-tags">{{ tag.tag_name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>



        <section class="embed-responsive px-md-5 px-sm-4 px-2 pt-2 pb-5">
            <div class="row px-3">
                {% if  request.user.is_authenticated %}
                    <a class="btn btn-success mx-3" href="{% url 'book:add_book' %}">Add Book</a>
                {% endif %}
                <div class="col-md-12 pt-5">
                    <div class="row">
                        {% for book in all_books %}
                            <div class="col-lg-2 col-md-3 col-sm-4 col-6">
                                <div class="card border-0" style="background-color:#F5F5F5">
                                    <a href="{% url 'book:book_details' book.book_slug %}">
                                        <img src="{{ book.book_image_url }}" class="card-img-top">
                                    </a>
                                    <div class="card-body px-0 pt-1">
                                        <p class="card-title my-0">{{ book.book_title }}</p>
                                        <p class="card-text text-muted">{{ book.book_author }}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>

    {% else %}
        <h2 class='text-muted text-center py-5'>New Summary will be added soon.</h2>      
    {% endif %}        



{% endblock content %}

book_app/templates/suggestion_view.html
{% extends 'base.html' %}

{% block title %} Suggestion and Recommendation - Short Summary {% endblock title %}

{% block content %}


	<section class='py-5 embed-responsive'>
		<div class='row'>
			<div class='col-lg-4  col-md-6 col-sm-8 col-10 offset-lg-4 offset-md-3 offset-sm-2 offset-1 bg-white'>
				<div class='pt-4 pb-3'>
					<p class="h4 text-center pb-4">Every Suggestion is Welcome</p>
					<form method="post">
					{% csrf_token %}
						{{ s_form.as_p }}
						<input type='submit' value='Suggest' class='btn btn-primary float-right mb-4 btn-block'>
					</form>
				</div>
			</div>
		</div>
	</section>
	


{% endblock content %}

book_app/templates/tag_details.html
{% extends 'base.html' %}

{% block title %} {{ tag.tag_name }} books - Short Summary {% endblock title %}

{% block content %}


    <section class="embed-responsive py-5 px-md-5 px-sm-4 px-2 ">
        <div class="row px-3">
            <h4 class="bg-light text-dark px-3 py-2 border">{{ tag.tag_name }} Books</h4>

            <div class="col-md-12 pt-5">
                <div class="row">
                    {% for book in tag_books %}
                        <div class="col-lg-2 col-md-3 col-sm-4 col-6">
                            <div class="card border-0">
                                <a href="{% url 'book:book_details' book.book_slug %}">
                                    <img src="{{ book.book_image_url }}" class="card-img-top">
                                </a>
                                <div class="card-body px-0 pt-1" style="background-color:#F5F5F5">
                                    <p class="card-title my-0">{{ book.book_title }}</p>
                                    <p class="card-text text-muted">{{ book.book_author }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

        </div>
    </section>


{% endblock content %}

book_app/templates/who_why.html
{% extends 'base.html' %}

{% block title %} Who & Why - Short Summary {% endblock title %}

{% block content %}


	<section class='py-5 px-4 px-md-5'>
		<div class='row'>
			<div class='col-md-8 offset-md-2 bg-white p-4 col-12'>
				<p class='lead'>
					Hey there, I  am Naveen Chahar. I believe the saying <span class='text-primary'>"books are the best friends of human." </span>
					<br><br>
					I am a Computer Science & Engineering student. I started reading books almost two years ago. Probably reading is the one of best decision I have ever taken. It satisfy my hunger for gathering knowledge from the greats.
					stress management, communication and many more. Now I have decided to share short summaries with all.
					<br><br>
					Reading on continuous basis is more powerful than reading occasionally.
					<br><br>
					<span class='h4 text-dark'>So, here's my plan</span>
					<br><br>
					 I will read minimum 2 books every month and post summary in most effective way so that I can post summaries of them. Surely, summaries are not the replacement of reading whole book,
					 instead summary provides the inside of book and it reflects what a book is all about.
					 <br><br>
					 I strongly recommend if you found any book summary really interesting and helpful then just read the whole book, In that way you will be benefited most.
					 <br><br>
					 Happy Reading!
				</p>
			</div>
		</div>

	</section>


{% endblock content %}